package org.ahocorasick;

import org.ahocorasick.trie.Emit;
import org.ahocorasick.trie.Trie;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;

public class main {
    public static void main(String[] args) throws IOException {

        ArrayList<ArrayList<String>> data = new ArrayList<ArrayList<String>>();
        String pathtable = "test.xlsx";

        FileInputStream fileInputStream = new FileInputStream(pathtable);
        XSSFWorkbook xssfWorkbook = new XSSFWorkbook(fileInputStream);
        XSSFSheet sheet = xssfWorkbook.getSheetAt(0);
        int rows = sheet.getLastRowNum();
        int cells = sheet.getRow(1).getLastCellNum();
        for (int r = 2; r <= rows; r++) {
            XSSFRow row = sheet.getRow(r);
            ArrayList<String> radek = new ArrayList<>();
            for (int c = 3; c <= cells - 1; c++) {
                XSSFCell cell = row.getCell(c);
                String value = cell.getStringCellValue();
                if (!value.equals("")) {
                    radek.add(value);
                }
            }
            data.add(radek);
        }

        Trie trie;
        {
            trie = Trie.builder().onlyWholeWords().ignoreCase().ignoreOverlaps()
                    .addKeyword("Business Continuity")
                    .addKeyword("incident response")
                    .addKeyword("policy development")
                    .addKeyword("Business Continuity Plan")
                    .addKeyword("BCP")
                    .addKeyword("improvisation")
                    .addKeyword("business processes")
                    .addKeyword("prevention")
                    .addKeyword("Data Analysis")
                    .addKeyword("data mining")
                    .addKeyword("cluster analysis")
                    .addKeyword("anomaly detection")
                    .addKeyword("security event log")
                    .addKeyword("information security log")
                    .addKeyword("system activity logs")
                    .addKeyword("evaluate data")
                    .addKeyword("describe data")
                    .addKeyword("illustrate data")
                    .addKeyword("summarize data")
                    .addKeyword("synthesis")
                    .addKeyword("data analysis")
                    .addKeyword("data collection")
                    .addKeyword("data representation")
                    .addKeyword("machine learning")
                    .addKeyword("data processing")
                    .addKeyword("big data")
                    .addKeyword("statistics")
                    .addKeyword("forecasting methodologies")
                    .addKeyword("Data Privacy")
                    .addKeyword("data anonymization")
                    .addKeyword("statistical disclosure control")
                    .addKeyword("privacy model")
                    .addKeyword("differential privacy")
                    .addKeyword("k-anonymity")
                    .addKeyword("masking")
                    .addKeyword("sensitive data")
                    .addKeyword("data protection")
                    .addKeyword("information privacy")
                    .addKeyword("P3P")
                    .addKeyword("Privacy-Enhancing Technologies")
                    .addKeyword("PET")
                    .addKeyword("privacy-by-design")
                    .addKeyword("Data Security")
                    .addKeyword("confidentialty")
                    .addKeyword("integrity")
                    .addKeyword("encryption")
                    .addKeyword("signature")
                    .addKeyword("key distribution")
                    .addKeyword("authentication")
                    .addKeyword("cryptographic algorithms")
                    .addKeyword("cryptographic concepts")
                    .addKeyword("security technologies")
                    .addKeyword("information security")
                    .addKeyword("data protection")
                    .addKeyword("information systems protection")
                    .addKeyword("confidentialty")
                    .addKeyword("integrity")
                    .addKeyword("Digital Forensics")
                    .addKeyword("digital evidence")
                    .addKeyword("digital forensic investigation")
                    .addKeyword("forensic investigation")
                    .addKeyword("Forensics")
                    .addKeyword("network forensics")
                    .addKeyword("data recovery")
                    .addKeyword("electronic evidence")
                    .addKeyword("computer-related evidence")
                    .addKeyword("forensics methods")
                    .addKeyword("forensics analysis")
                    .addKeyword("criminal methodologies")
                    .addKeyword("criminal investigation procedures")
                    .addKeyword("Identity Management")
                    .addKeyword("Active Directory")
                    .addKeyword("authentication systems")
                    .addKeyword("authorization systems")
                    .addKeyword("identity & access management")
                    .addKeyword("Directory services")
                    .addKeyword("Azure AD")
                    .addKeyword("identity and access management")
                    .addKeyword("access privileges")
                    .addKeyword("authorized access")
                    .addKeyword("AD")
                    .addKeyword("Incident Management")
                    .addKeyword("incident management")
                    .addKeyword("incident impact")
                    .addKeyword("incident remediation")
                    .addKeyword("IT incident")
                    .addKeyword("security incident")
                    .addKeyword("security issue")
                    .addKeyword("incident response")
                    .addKeyword("Incident Management and Response")
                    .addKeyword("Respond to security events")
                    .addKeyword("log files")
                    .addKeyword("Secure Operation Centres")
                    .addKeyword("SOCs")
                    .addKeyword("Computer Security Incident Response Teams")
                    .addKeyword("CSIRTs")
                    .addKeyword("incident cycle")
                    .addKeyword("Information Systems and Network Security")
                    .addKeyword("network security")
                    .addKeyword("platform security")
                    .addKeyword("security infrastructure")
                    .addKeyword("Security Incident and Event Management")
                    .addKeyword("could security")
                    .addKeyword("web security")
                    .addKeyword("System security")
                    .addKeyword("Intrusion detection & prevention systems")
                    .addKeyword("IDS")
                    .addKeyword("IPS")
                    .addKeyword("Secure Web Gateway")
                    .addKeyword("Data Loss Prevention")
                    .addKeyword("anti-virus")
                    .addKeyword("anti-malware")
                    .addKeyword("Network Infrastructure")
                    .addKeyword("endpoint security")
                    .addKeyword("Endpoint protection")
                    .addKeyword("Cloud environments")
                    .addKeyword("security control")
                    .addKeyword("offensive security practices")
                    .addKeyword("defensive security practices")
                    .addKeyword("security-related standards")
                    .addKeyword("ESET")
                    .addKeyword("Information Security Controls Assessment")
                    .addKeyword("Iperf")
                    .addKeyword("Benchmarks")
                    .addKeyword("Performance simulation")
                    .addKeyword("Authorization tests")
                    .addKeyword("Stress tests")
                    .addKeyword("IT audit")
                    .addKeyword("Perform audits")
                    .addKeyword("organize audits")
                    .addKeyword("audit process")
                    .addKeyword("audit review")
                    .addKeyword("ISO audits")
                    .addKeyword("security related audits")
                    .addKeyword("system tests")
                    .addKeyword("audit frameworks")
                    .addKeyword("audit certifications")
                    .addKeyword("assess the effectiveness")
                    .addKeyword("assess the practicality")
                    .addKeyword("protect auditing information")
                    .addKeyword("assess software security")
                    .addKeyword("assess hardware security")
                    .addKeyword("review software security")
                    .addKeyword("review hardware security")
                    .addKeyword("Intelligence Analysis")
                    .addKeyword("analytic tradecraft")
                    .addKeyword("technical analysis")
                    .addKeyword("technical reporting")
                    .addKeyword("feedback")
                    .addKeyword("customized analysis")
                    .addKeyword("Directorate of Intelligence")
                    .addKeyword("collecting information")
                    .addKeyword("utilizing information")
                    .addKeyword("analytical skills")
                    .addKeyword("Law, Policy, and Ethics")
                    .addKeyword("GDPR")
                    .addKeyword("General Data Protection Regulation")
                    .addKeyword("national regulations")
                    .addKeyword("international regulations")
                    .addKeyword("HIPAA")
                    .addKeyword("information security policy")
                    .addKeyword("Information Security Program")
                    .addKeyword("Information Security Awareness Program")
                    .addKeyword("compliance")
                    .addKeyword("governance")
                    .addKeyword("security policies")
                    .addKeyword("jurisdiction requirements")
                    .addKeyword("compliance check")
                    .addKeyword("information security policies and procedures")
                    .addKeyword("laws")
                    .addKeyword("regulations")
                    .addKeyword("legal framework")
                    .addKeyword("legislations")
                    .addKeyword("copyright")
                    .addKeyword("property rights")
                    .addKeyword("patent filing")
                    .addKeyword("standards’ requirements")
                    .addKeyword("legal requirements")
                    .addKeyword("Law, Policy, and Ethics")
                    .addKeyword("ethical cybersecurity organisation requirements")
                    .addKeyword("legal compliance requirements")
                    .addKeyword("legal compliance practices")
                    .addKeyword("Physical Device Security")
                    .addKeyword("Device certification")
                    .addKeyword("Restricted physical access")
                    .addKeyword("Remote access")
                    .addKeyword("Device port security")
                    .addKeyword("Camera")
                    .addKeyword("biometric")
                    .addKeyword("physical access systems")
                    .addKeyword("room audit")
                    .addKeyword("Visitor Logs")
                    .addKeyword("Sensors")
                    .addKeyword("authentication")
                    .addKeyword("alarm")
                    .addKeyword("electronic devices")
                    .addKeyword("Risk Management")
                    .addKeyword("risk assessment")
                    .addKeyword("mitigation")
                    .addKeyword("security risks")
                    .addKeyword("vendor evaluation")
                    .addKeyword("risk register")
                    .addKeyword("risk analysis")
                    .addKeyword("maturity models")
                    .addKeyword("risk guidelines")
                    .addKeyword("risk sharing options")
                    .addKeyword("mitigate risks")
                    .addKeyword("Testing and Evaluation")
                    .addKeyword("AST")
                    .addKeyword("Application Security Testing")
                    .addKeyword("Penetration test")
                    .addKeyword("pentest")
                    .addKeyword("test and identify")
                    .addKeyword("application security controls")
                    .addKeyword("technical evaluations")
                    .addKeyword("Security scanning")
                    .addKeyword("vulnerability detection")
                    .addKeyword("security assessment")
                    .addKeyword("Ethical Hacking")
                    .addKeyword("vulnerability scan")
                    .addKeyword("CTI")
                    .addKeyword("exploits")
                    .addKeyword("social engineering")
                    .addKeyword("testing the effectiveness")
                    .addKeyword("evaluating the effectiveness")
                    .addKeyword("malware analysis tools")
                    .addKeyword("security vulnerabilities")
                    .addKeyword("Threat Analysis")
                    .addKeyword("vulnerability analysis")
                    .addKeyword("vulnerability management")
                    .addKeyword("threats analysis")
                    .addKeyword("threat management")
                    .addKeyword("threat research")
                    .addKeyword("threat intelligence")
                    .addKeyword("threat hunting")
                    .addKeyword("vulnerability scanning")
                    .addKeyword("vulnerability testing")
                    .addKeyword("potential threats")
                    .addKeyword("vulnerability research")
                    .addKeyword("attack vectors")
                    .addKeyword("threat tactics")
                    .addKeyword("attacker techniques")
                    .addKeyword("Threat Modelling")
                    .addKeyword("threat information")
                    .addKeyword("malware analysis")
                    .addKeyword("reverse engineering")
                    .addKeyword("threats taxonomies")
                    .addKeyword("counterintelligence investigations")
                    .addKeyword("Asset and Inventory Management")
                    .addKeyword("Active Directory")
                    .addKeyword("data storage within systems")
                    .addKeyword("protections within systems")
                    .addKeyword("up-to-date system")
                    .addKeyword("Enterprise asset management")
                    .addKeyword("EAM")
                    .addKeyword("disposing of assets")
                    .addKeyword("Database Administration")
                    .addKeyword("Oracle")
                    .addKeyword("MySQL")
                    .addKeyword("SQLite")
                    .addKeyword("MSSQL")
                    .addKeyword("MS SQL")
                    .addKeyword("database")
                    .addKeyword("database administration")
                    .addKeyword("cloud")
                    .addKeyword("SQL")
                    .addKeyword("PostgreSQL")
                    .addKeyword("phpmyadmin")
                    .addKeyword("Microsoft SQL Server")
                    .addKeyword("Enterprise Architecture")
                    .addKeyword("Structure blueprint")
                    .addKeyword("Standardization")
                    .addKeyword("Technology perspective")
                    .addKeyword("Framework systems")
                    .addKeyword("Connectivity")
                    .addKeyword("Microsoft 365")
                    .addKeyword("Security Applications")
                    .addKeyword("security planning")
                    .addKeyword("Control systems")
                    .addKeyword("forensic analysis")
                    .addKeyword("Cloud security")
                    .addKeyword("Security control")
                    .addKeyword("security architecture reference models")
                    .addKeyword("systems design")
                    .addKeyword("Draw architectural specifications")
                    .addKeyword("Network Management")
                    .addKeyword("Network security")
                    .addKeyword("Network configuration")
                    .addKeyword("Troubleshooting")
                    .addKeyword("Monitoring")
                    .addKeyword("Design")
                    .addKeyword("network devices")
                    .addKeyword("network infrastructure")
                    .addKeyword("routing")
                    .addKeyword("penetration testing")
                    .addKeyword("Risk management")
                    .addKeyword("switching")
                    .addKeyword("Network implementation")
                    .addKeyword("TTP frameworks")
                    .addKeyword("Operating Systems")
                    .addKeyword("Windows")
                    .addKeyword("Linux")
                    .addKeyword("Unix")
                    .addKeyword("Android")
                    .addKeyword("iOS")
                    .addKeyword("MacOS")
                    .addKeyword("Platform security")
                    .addKeyword("System Internals")
                    .addKeyword("operating systems")
                    .addKeyword("multiplatform")
                    .addKeyword("systems development life cycle")
                    .addKeyword("operating system vulnerabilities")
                    .addKeyword("virtualization")
                    .addKeyword("operating clouds")
                    .addKeyword("Software Development")
                    .addKeyword("Python")
                    .addKeyword("C/C++")
                    .addKeyword("Java")
                    .addKeyword("Go")
                    .addKeyword("R")
                    .addKeyword("development")
                    .addKeyword("Software engineering")
                    .addKeyword("Agile Secure Development Lifecycle")
                    .addKeyword("programming knowledge")
                    .addKeyword("assembly language")
                    .addKeyword("script language")
                    .addKeyword("programming")
                    .addKeyword("Develop tools")
                    .addKeyword("scripting languages")
                    .addKeyword("programming languages")
                    .addKeyword("secure coding practices")
                    .addKeyword("System Administration")
                    .addKeyword("Bash")
                    .addKeyword("PowerShell")
                    .addKeyword("Coordination")
                    .addKeyword("Bypass security")
                    .addKeyword("Statistical analysis")
                    .addKeyword("analyse systems")
                    .addKeyword("spot weaknesses")
                    .addKeyword("operating systems")
                    .addKeyword("IT/OT")
                    .addKeyword("computer networks")
                    .addKeyword("networking protocols")
                    .addKeyword("Collaborate and Communicate")
                    .addKeyword("Video demonstrations")
                    .addKeyword("Nonverbal cues")
                    .addKeyword("Presentation")
                    .addKeyword("Practical examples")
                    .addKeyword("Interpersonal skills")
                    .addKeyword("verbal communication")
                    .addKeyword("written communication")
                    .addKeyword("intelligibility")
                    .addKeyword("Graphs")
                    .addKeyword("infographics")
                    .addKeyword("teamwork")
                    .addKeyword("helpfulness")
                    .addKeyword("effectively expressing information")
                    .addKeyword("disseminate")
                    .addKeyword("Education and Training Delivery")
                    .addKeyword("Educational material")
                    .addKeyword("workshop")
                    .addKeyword("knowledge sharing")
                    .addKeyword("trainings")
                    .addKeyword("reports")
                    .addKeyword("security awareness and guidance")
                    .addKeyword("Knowledge transfer")
                    .addKeyword("information sharing")
                    .addKeyword("Share knowledge")
                    .addKeyword("professional trainings")
                    .addKeyword("Mentoring")
                    .addKeyword("Guides")
                    .addKeyword("learning courses")
                    .addKeyword("pedagogical methods")
                    .addKeyword("curricula")
                    .addKeyword("exercises")
                    .addKeyword("training")
                    .addKeyword("training resources")
                    .addKeyword("Organizational Awareness")
                    .addKeyword("cybersecurity trends")
                    .addKeyword("influencers")
                    .addKeyword("power relationships")
                    .addKeyword("organisational structure")
                    .addKeyword("culture")
                    .addKeyword("social media")
                    .addKeyword("risk-aware environment")
                    .addKeyword("Policy Development")
                    .addKeyword("information security management system")
                    .addKeyword("ISMS")
                    .addKeyword("laws")
                    .addKeyword("regulation")
                    .addKeyword("compliance")
                    .addKeyword("policies")
                    .addKeyword("policy development")
                    .addKeyword("Project Management")
                    .addKeyword("Project roadmap")
                    .addKeyword("project plan")
                    .addKeyword("consortium management")
                    .addKeyword("partnership management")
                    .addKeyword("opportunity canvas")
                    .addKeyword("Mind Map")
                    .addKeyword("project budgeting")
                    .addKeyword("predict")
                    .addKeyword("prediction")
                    .addKeyword("long term")
                    .addKeyword("short term")
                    .addKeyword("planning")
                    .addKeyword("cybersecurity strategy")
                    .addKeyword("Strategic Relationship Management")
                    .addKeyword("cyber diplomacy")
                    .addKeyword("stakeholders")
                    .addKeyword("strategy")
                    .addKeyword("SRM")
                    .addKeyword("stategic framework")
                    .addKeyword("SLA")
                    .addKeyword("Service-level agreement")
                    .addKeyword("Subject Matter Experts")
                    .addKeyword("Workforce Management")
                    .addKeyword("human resource management")
                    .addKeyword("psychology")
                    .addKeyword("benefits")
                    .addKeyword("performance review")
                    .addKeyword("personal development")
                    .addKeyword("HR")
                    .addKeyword("productive workforce")
                    .addKeyword("career pathing")
                    .addKeyword("interviewing techniques")
                    .addKeyword("lead teams")
                    .addKeyword("Work under pressure")
                    .addKeyword("conduct interviews")
                    .addKeyword("Problem solving and Critical Thinking")
                    .addKeyword("anticipate")
                    .addKeyword("new ideas")
                    .addKeyword("solutions")
                    .addKeyword("sound judgment")
                    .addKeyword("objective recommendations")
                    .addKeyword("objective decisions")
                    .addKeyword("make inferences")
                    .addKeyword("draw conclusions")
                    .addKeyword("plan")
                    .addKeyword("creativity")
                    .addKeyword("outside the box")
                    .addKeyword("troubleshoot")
                    .addKeyword("solve complex problems")
                    .addKeyword("solve security challenges")
                    .addKeyword("Technology Fluency")
                    .addKeyword("best practice")
                    .addKeyword("innovation")
                    .addKeyword("trends")
                    .addKeyword("research")
                    .addKeyword("development")
                    .addKeyword("RDI")
                    .addKeyword("espionage threats")
                    .addKeyword("coercion threats")
                    .addKeyword("self-learning")
                    .addKeyword("effective use of technology")
                    .addKeyword("up to date")
                    .addKeyword("cybersecurity trends")
                    .build();
        }
        Path filesName = Path.of("test.txt");

        // Now calling Files.readString() method to
        // read the file
        String str = Files.readString(filesName);

        Collection<Emit> emits = trie.parseText(str);
        System.out.println(emits);

        String wordsy = emits.toString();
        wordsy = wordsy.replaceAll("[^A-Za-z ,]+", "");

        String[] arrOfStr = wordsy.split(",", 0);

//        for (String a : arrOfStr) {
//            System.out.print(a);
//        }

        for (int i = 0; i < arrOfStr.length; i++) {
            arrOfStr[i] = arrOfStr[i].trim();
        }

        System.out.println("");


        int k = 0;
        int[] counters = new int[data.size()];
        Arrays.fill(counters, 0);


        while (k <= (arrOfStr.length) - 1) {
            for (int i = 0; i < data.size(); i++) {
                for (int j = 0; j < data.get(i).size(); j++) {
                    if (k == arrOfStr.length) {
                        break;
                    }
                    if (data.get(i).get(j).equals(arrOfStr[k])) {
                       // System.out.println(data.get(i).get(0));
                        counters[i]=counters[i]+1;
                       // System.out.println(k);
                        k++;

                    }
                }
            }
        }
        for (int i =0; i< counters.length; i++){
            if(counters[i]>0) {
                System.out.println("Number of words from " + data.get(i).get(0) + " is: " + counters[i]);
            }
        }
    }
}
